# Generated by Django 6.0 on 2026-08-24 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuporteMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Membro de suporte',
                'verbose_name_plural': 'Equipe de suporte',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=150, unique=True)),
                ('posicao', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_rca', models.CharField(blank=True, max_length=20, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_sup', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_supervisor', models.CharField(blank=True, max_length=150, null=True)),
                ('codcli', models.CharField(blank=True, max_length=20, null=True)),
                ('fantasia', models.CharField(blank=True, max_length=150, null=True)),
                ('data_pedido', models.DateField(blank=True, null=True)),
                ('hora_pedido', models.CharField(blank=True, max_length=20, null=True)),
                ('vlatend', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('codcob', models.CharField(blank=True, max_length=10, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('obs1', models.TextField(blank=True, null=True)),
                ('obs2', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('liberar', 'Liberar'), ('tratar', 'Tratar'), ('recomposicao', 'Recomposição'), ('prazo', 'Prazo'), ('nivea', 'Nívea'), ('bonificacao', 'Bonificação'), ('sem_categoria', 'Sem categoria')], default='sem_categoria', max_length=20)),
                ('categoria_manual', models.BooleanField(default=False)),
                ('motivo_categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('classificado_ia', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atribuido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='triagem.suportemembro')),
            ],
            options={
                'ordering': ['-data_pedido'],
            },
        ),
    ]
